# Backend Dockerfile
FROM node:18-alpine

WORKDIR /app

# Copia package.json e installa dipendenze
COPY backend/package*.json ./
RUN npm config set fetch-timeout 120000 && npm config set fetch-retry-mintimeout 20000 && npm install --omit=dev

# Copia codice sorgente
COPY backend/src ./src

# Espone porta
EXPOSE 5000

# Start app
CMD ["node", "src/server.js"]
